env:
  browser: true
  es6: true
extends: 'eslint:recommended'
globals:
  chrome: true
  module: true
  __dirname: true
  require: true
  global: true
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
